### ISSUE TITLE
大佬辛苦问个问题

### ISSUE THREAD

**Issue by lhbdhr** [AutoCONFIG/lala-openwrt#1]
### Describe the bug

大佬辛苦问个问题，我在恩山看到你对miniupnpd的回答。https://www.right.com.cn/forum/thread-8273627-1-1.html
有个问题想咨询一下。
我的路由器没有公网IP，但是NAT类型是full cone，
我使用nat打洞工具natmap可以打洞成功。可以通过公网IP+端口访问我的内网。
但是natmap使用很麻烦，需要手动配置端口，而且端口变动，还需要重新配置。没有upnp或者nat-pmp方便。

miniupnp有没有这样的功能。
我看你在帖子里说openwrt 22.03不可以，那我用之前的固件可以吗？
你这个固件我的路由器不适配，还需要重新编译。。。

### OpenWrt version

2203

### OpenWrt target/subtarget

openwrt官方固件

### Device

XIAOMI AC2100 CPU 7621

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by AutoCONFIG** [comment]
如果入口网关获得的是私网地址的话，则NAT穿透很被动，有很多影响因素。NAT类型的测试工具都是UDP实现，TCP的NAT类型情况并不可知，但是鉴于您已经通过NATMap成功打洞，如果是TCP协议，则可以认为您的TCP NAT类型至少为锥形。
并不是说openwrt 22.03的upnp功能不可用，只是多了一个公网检测环节，没有公网地址而启用upnp，可能只是心理安慰
upnp并不能对上级NAT起作用，他是用在当前路由器有公网IP的情况，给本路由器自动添加NAT映射（端口转发）以达到或者接近公网环境，所以对于路由器没有公网IP，upnp则完全不起作用。
nat-pmp与upnp原理类似，都是对本路由器添加NAT映射，通常upnp与nat-pmp功能绑定
所以想突破运营商NAT限制，可以通过natmap维持NAT映射端口的建立，以实现接受公网数据。
natmap并不算很麻烦，因为可以实现自动对内网固定目标端口的转发（可能需要防火墙支持），只是每当第一次使用时需要手动配置执行，这个可以通过启动项或者计划任务脚本实现自动化
转发可参考：https://zhuanlan.zhihu.com/p/577659705

**Comment by lhbdhr** [comment]
啊，懂了。
意思就是 如果没有公网ip，miniupnp完全没用是吧？
只有当主路由有公网IP，然后内网用miniupnp才会有用是吧？

我还以为 miniupnp 会起到和 NATMap 一样的作用，可以帮忙在公网打洞呢。
我的NATMap完全跑通了，可以正常使用，只是缺少自动化，我研究一下吧。
谢谢啦。
